package cn.edu.upc.hyz.dao;

import cn.edu.upc.hyz.model.RightRoleInput;
import cn.edu.upc.hyz.model.Role;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    //设置deflag=1，删除角色
    void updateRoleName(RightRoleInput rightRoleInput);
    Role selectRoles(Integer id);

    int selectLastInsert();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Thu Apr 02 16:19:53 CST 2020
     */
    int updateByPrimaryKey(Role record);

    //添加的方法
    //删除
    boolean deleteRoleLN(Role record);
    //获取所有的role
    List<Role> selectAllRole();
    //更新role
    boolean updateRole(Role record);
    //插入新的role
    boolean insertRole(Role record);




}